query myAccountMinProfile {
	myAccount {
		_id
		account {
			username
			tag
			private
		}
		profile {
			bannerUrl
			pictureUrl
			description
			followingIds
			followerIds
			badges
			linkedProfiles
		}
		status
	}
}
