mutation updateProfile($newname: String, $newtag: String, $newdes: String) {
	updateProfile(name: $newname, tag: $newtag, description: $newdes) {
		_id
		account {
			username
			tag
		}
		profile {
			description
			bannerUrl
			pictureUrl
		}
	}
}
