mutation uploadSingle($file: Upload!, $type: String!) {
	singleUpload(file: $file, type: $type) {
		user {
			_id
			account {
				username
				tag
				private
			}
			profile {
				bannerUrl
				pictureUrl
				description
				followingIds
				followerIds
				badges
				linkedProfiles
			}
			social {
				postIds
				blogIds
			}
			status
		}
		file {
			filename
		}
	}
}
